version: '3'
services:
  backend:
    build: ./apps/backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "4000:4000"
  frontend:
    build: ./apps/frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"